### ISSUE TITLE
add-pr-approval-label should support CODEOWNERS file

### ISSUE THREAD

**Issue by sumitanvekar** [ExpediaGroup/github-helpers#28]
**Describe the feature**
add-pr-approval-label supports using team name but it would be desirable to use CODEOWNERS as list of CORE approvers

**Rational**
Current behaviour requires team creation so repositories which support CODEOWNERS file will have to maintain list of owners in 2 places.

**Comment by danadajian** [comment]
This is a really great suggestion! Let me know if you want to work on this, otherwise I can try to implement this feature.

**Comment by sumitanvekar** [comment]
I can work on it.
