### ISSUE TITLE
allow create-pr-comment to overwrite its own comments

### ISSUE THREAD

**Issue by aschwenn** [ExpediaGroup/github-helpers#57]
**Describe the feature**

It would be nice if there was functionality to allow a `create-pr-comment` to overwrite its own comments.

**Rational**

It likely wouldn't be very difficult to add and could expand functionality of the helper.

**Example Scenario**

I'm running on PR check multiple times on a pull request, and I want to leave a comment with a simplified version of the results so that users don't have to parse the run output. However, I don't want a ton of near-identical comments popping up.

Functionally, this would be similar to how `danger` automatically overwrites its PR comments.

**Comment by danadajian** [comment]
@aschwenn Were you thinking the helper would query for a comment with a certain body and update it?

**Comment by danadajian** [comment]
We should be able to use `octokit.rest.issues.updateComment()` for this
